services:
  employee-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - employee-network

networks:
  employee-network:
    driver: bridge